#!/usr/bin/env python3
import argparse
import sys
import time
import os


# global variables
parser = argparse.ArgumentParser()


def arguments():
    # POSITIONAL
    parser.add_argument(
            "minutes",
            help="minutes your tea takes to finish",
            type=int)

    # OPTIONAL
    parser.add_argument(
            "--version",
            version="1.0.1",
            action="version")

    args = parser.parse_args()

    if args.minutes < 0:
        print("warning! argument: 'minutes' should not be negative")
        sys.exit(1)


def main():
    args = parser.parse_args()
    seconds = args.minutes * 60 - 1

    for s in range(seconds, 0, -1):
        time.sleep(1)
        m = s // 60
        s = s % 60

        print("\rtime remainig: %0.2dm %0.2ds " % (m, s), end='', flush=True)

    print("\nYour tea is done!")
    file_name = os.path.basename(__file__).title()
    os.system("notify-send \"" + file_name + "\" \"Your tea is done!\"")
    os.system("spd-say \"Your tea is done!\"")

arguments()
main()
