#!/usr/bin/env python3


import argparse
import os
import signal
import sys
import time


# global variables
parser = argparse.ArgumentParser()


def clear_print(msg):
    print("\r                                                                                ", end="", flush=True)
    print("\r" + msg, end="", flush=True)


def sigint_handler(signum, frame):
    clear_print("Timer aborted.\n")
    exit(1)


signal.signal(signal.SIGINT, sigint_handler)


def arguments():
    # POSITIONAL
    parser.add_argument(
            "minutes",
            help="minutes your tea takes to finish",
            type=int)

    # OPTIONAL
    parser.add_argument(
            "--version",
            version="1.0.2",
            action="version")

    args = parser.parse_args()

    if args.minutes < 0:
        clear_print("warning! argument: 'minutes' should not be negative")
        sys.exit(1)


def main():
    args = parser.parse_args()
    seconds = args.minutes * 60 - 1

    for s in range(seconds, -1, -1):
        time.sleep(1)
        m = s // 60
        s = s % 60

        clear_print("\rTime remaining: %0.2dm %0.2ds " % (m, s))

    now = time.localtime()
    clear_print("\r%0.2d:%0.2d - Your tea is ready.\n" % (now.tm_hour, now.tm_min))

    os.system("notify-send \"Your tea is ready!\"")


arguments()
main()
