#!/usr/bin/env python3
import argparse
import sys
import time
import os


# global variables
parser = argparse.ArgumentParser()


def arguments():
    # POSITIONAL
    parser.add_argument(
            "minutes",
            help="minutes your tea takes to finish",
            type=int)

    # OPTIONAL
    parser.add_argument(
            "--version",
            version="1.0.2",
            action="version")

    args = parser.parse_args()

    if args.minutes < 0:
        print("warning! argument: 'minutes' should not be negative")
        sys.exit(1)


def main():
    args = parser.parse_args()
    seconds = args.minutes * 60 - 1

    for s in range(seconds, -1, -1):
        time.sleep(1)
        m = s // 60
        s = s % 60

        print("\rTime remaining: %0.2dm %0.2ds " % (m, s), end="", flush=True)

    # clear line for the final message.
    print("\r                              ", end="", flush=True)

    now = time.localtime()
    message = "\r%0.2d:%0.2d - Your tea is ready!"
    message = message % (now.tm_hour, now.tm_min)

    print(message)
    os.system("notify-send \"Your tea is ready!\"")


arguments()
main()
