! ------------------------------------------------------------------------------
! Default Color Theme (base16 based)
! ------------------------------------------------------------------------------
rofi.color-enabled: true
rofi.color-window: #181818, #e8e8e8, #e8e8e8
rofi.color-normal: #181818, #e8e8e8, #282828, #585858, #e8e8e8
rofi.color-active: #181818, #7cafc2, #282828, #585858, #7cafc2
rofi.color-urgent: #181818, #ab4642, #282828, #585858, #ab4642
